name: Build and deploy documentation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - docs/**
      - projects/**
  push:
    branches:
      - main
    paths:
      - docs/**
      - projects/**

jobs:
  code-analyse:
    name: Code analyse
    uses: ./.github/workflows/code-analyse.yml

  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest

    needs:
      - code-analyse

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: True

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build
          tar \
            --dereference --hard-dereference \
            --directory docs/_build \
            -cvf "${RUNNER_TEMP}/artifact.tar" \
            .

      - name: Upload GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error

  deploy-docs:
    name: Deploy documentation
    runs-on: ubuntu-latest

    needs:
      - build-docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write     # to deploy to Pages
      id-token: write  # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
